#include "CreatureProcessor.h"
#include <juce_audio_utils/juce_audio_utils.h>
#include "shared/ui/LsseProductEditor.h"
#include "shared/state/StateMigration.h"

namespace { constexpr int stateVersion=3; }
CreatureAudioProcessor::CreatureAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),parameters(*this,nullptr,"CREATURE_STATE",createParameterLayout()){}
void CreatureAudioProcessor::prepareToPlay(double newSampleRate,int){sampleRate=newSampleRate;samplePosition=0.0;const auto seed=(std::uint32_t)parameters.getRawParameterValue("seed")->load();for(std::size_t i=0;i<engines.size();++i)engines[i].prepare(sampleRate,seed+(std::uint32_t)i*7919u);}
bool CreatureAudioProcessor::isBusesLayoutSupported(const BusesLayout& b)const{const auto i=b.getMainInputChannelSet(),o=b.getMainOutputChannelSet();return i==o&&(o==juce::AudioChannelSet::mono()||o==juce::AudioChannelSet::stereo());}
void CreatureAudioProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&)
{
    juce::ScopedNoDenormals n;if(sourceResetRequested.exchange(false,std::memory_order_acq_rel))samplePosition=0.0;const auto pct=[&](const char* id){return parameters.getRawParameterValue(id)->load()/100.0f;};
    const auto breath=pct("breath"),growl=pct("growl"),follow=pct("follow"),throat=pct("throat"),formant=pct("formant"),vowel=pct("vowel"),chatter=pct("chatter"),body=pct("body"),activity=pct("activity"),aggression=pct("aggression"),variation=pct("variation"),size=pct("size"),anatomy=pct("anatomy"),stereo=pct("stereo");
    const auto sourceMode=static_cast<int>(parameters.getRawParameterValue("source_mode")->load());const auto sourceBlend=pct("source_blend");const auto sampleLevel=pct("sample_level");const auto samplePitch=parameters.getRawParameterValue("sample_pitch")->load();const auto sampleLoop=parameters.getRawParameterValue("sample_loop")->load()>0.5f;const auto loaded=sourceSample.get();const auto sampleStep=loaded!=nullptr?loaded->sampleRate/sampleRate*std::pow(2.0,samplePitch/12.0):0.0;
    const auto tone=parameters.getRawParameterValue("tone")->load()/100.0f;const auto behavior=static_cast<int>(parameters.getRawParameterValue("behavior")->load());const auto mix=pct("mix");const auto gain=std::pow(10.0f,parameters.getRawParameterValue("output")->load()/20.0f);const auto channels=juce::jmin(b.getNumChannels(),static_cast<int>(engines.size()));
    for(int s=0;s<b.getNumSamples();++s){const auto sampleAvailable=loaded!=nullptr&&(sampleLoop||samplePosition<loaded->audio.getNumSamples());for(int c=0;c<channels;++c){const auto raw=b.getSample(c,s);const auto dry=std::isfinite(raw)?raw:0.0f;const auto sample=sampleAvailable?lsse::audio::UserSampleSlot::readLinear(*loaded,c,samplePosition)*sampleLevel:0.0f;auto excitation=dry;if(sourceMode==1&&sampleAvailable)excitation=sample;else if(sourceMode==2&&sampleAvailable)excitation=dry+(sample-dry)*sourceBlend;const auto side=channels==2?(c==0?-1.0f:1.0f):0.0f;const auto wet=engines[(std::size_t)c].process(excitation,breath,growl,follow,throat,formant,vowel,chatter,body,activity,aggression,variation,juce::jlimit(0.0f,1.0f,size+(anatomy-0.5f)*0.25f+side*stereo*0.035f),tone,behavior);b.setSample(c,s,(dry+(wet-dry)*mix)*gain);}if(sampleAvailable)samplePosition+=sampleStep;if(loaded!=nullptr&&sampleLoop&&samplePosition>=loaded->audio.getNumSamples())samplePosition=std::fmod(samplePosition,static_cast<double>(loaded->audio.getNumSamples()));}
}
juce::AudioProcessorEditor* CreatureAudioProcessor::createEditor()
{
    using namespace lsse::ui;
    return new ProductEditor (*this, parameters, "CREATURE", "Fictional anatomy and reactive vocal gesture", juce::Colour (0xff75d68b),
        { { "Source", { "source_mode", "source_blend", "sample_level", "sample_pitch", "sample_loop" } },
          { "Anatomy", { "anatomy", "size", "throat", "formant", "vowel" } },
          { "Voice", { "breath", "growl", "chatter", "body", "tone" } },
          { "Behavior", { "behavior", "activity", "aggression", "variation", "follow" } },
          { "Ecology", { "seed", "stereo", "mix", "output" } } },
        { { "Sleeping Giant", { {"mix",1},{"size",.9f},{"breath",.58f},{"growl",.3f},{"activity",.14f},{"body",.86f} } },
          { "Alert Swarm", { {"mix",1},{"size",.2f},{"chatter",.88f},{"activity",.9f},{"variation",.76f},{"stereo",1} } },
          { "Throat Signal", { {"mix",1},{"throat",.9f},{"formant",.78f},{"vowel",.65f},{"growl",.72f},{"follow",.85f} } } },
        { { "LOAD SOURCE", [this]{chooseSourceSample();} }, { "CLEAR SOURCE", [this]{clearSourceSample();} } });
}
void CreatureAudioProcessor::chooseSourceSample(){if(fileChooser!=nullptr)return;fileChooser=std::make_unique<juce::FileChooser>("Load CREATURE source",juce::File::getSpecialLocation(juce::File::userMusicDirectory),"*.wav;*.aif;*.aiff;*.flac",true);fileChooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const juce::FileChooser&c){const auto f=c.getResult();if(f.existsAsFile())loadSourceSample(f);fileChooser.reset();});}
void CreatureAudioProcessor::clearSourceSample(){sourceSample.clear();sourceResetRequested.store(true,std::memory_order_release);const juce::ScopedLock lock(sourcePathLock);sourcePath.clear();}
bool CreatureAudioProcessor::loadSourceSample(const juce::File&f){if(!sourceSample.load(f))return false;sourceResetRequested.store(true,std::memory_order_release);const juce::ScopedLock lock(sourcePathLock);sourcePath=f.getFullPathName();return true;}
void CreatureAudioProcessor::getStateInformation(juce::MemoryBlock&d){auto s=parameters.copyState();s.setProperty("stateVersion",stateVersion,nullptr);{const juce::ScopedLock lock(sourcePathLock);s.setProperty("sourceSample",sourcePath,nullptr);}if(auto x=s.createXml())copyXmlToBinary(*x,d);}
void CreatureAudioProcessor::setStateInformation(const void*d,int z){if(auto x=getXmlFromBinary(d,z);x&&x->hasTagName(parameters.state.getType())){auto s=juce::ValueTree::fromXml(*x);parameters.replaceState(lsse::state::mergeParameterState(parameters.copyState(),s));const auto path=s.getProperty("sourceSample").toString();if(path.isNotEmpty())loadSourceSample(juce::File(path));else clearSourceSample();}}
juce::AudioProcessorValueTreeState::ParameterLayout CreatureAudioProcessor::createParameterLayout(){juce::AudioProcessorValueTreeState::ParameterLayout l;const auto pct=juce::AudioParameterFloatAttributes{}.withLabel("%");auto p=[&](const char*id,const char*n,float v){l.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{id,1},n,juce::NormalisableRange<float>{0,100,0.1f},v,pct));};l.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"source_mode",1},"SOURCE",juce::StringArray{"LIVE","SAMPLE","HYBRID"},0));p("source_blend","SOURCE BLEND",50);p("sample_level","SAMPLE LEVEL",70);l.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{"sample_pitch",1},"SAMPLE PITCH",juce::NormalisableRange<float>{-24,24,0.1f},0,juce::AudioParameterFloatAttributes{}.withLabel("st")));l.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{"sample_loop",1},"SAMPLE LOOP",true));p("anatomy","ANATOMY",50);p("size","SIZE",50);p("throat","THROAT",45);p("formant","FORMANT",50);p("vowel","VOWEL",50);p("breath","BREATH",25);p("growl","GROWL",35);p("chatter","CHATTER",10);p("body","BODY",55);l.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"behavior",1},"BEHAVIOR",juce::StringArray{"IDLE","ALERT","ATTACK","RETREAT"},0));p("activity","ACTIVITY",40);p("aggression","AGGRESSION",30);p("variation","VARIATION",25);p("follow","FOLLOW",70);l.add(std::make_unique<juce::AudioParameterInt>(juce::ParameterID{"seed",1},"SEED",1,65535,1977));p("stereo","STEREO",100);l.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{"tone",1},"TONE",juce::NormalisableRange<float>{-100,100,0.1f},0));p("mix","MIX",0);l.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{"output",1},"OUTPUT",juce::NormalisableRange<float>{-24,6,0.1f},0,juce::AudioParameterFloatAttributes{}.withLabel("dB")));return l;}
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new CreatureAudioProcessor();}
